version: "3.9"

services:
  ##### Grafana for visualization #####
  grafana:
    image: grafana/grafana:9.3.1
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./config/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana-data:/var/lib/grafana

  ##### Prometheus for metrics #####
  prometheus:
    image: prom/prometheus:v2.30.3
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=remote-write-receiver
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  ##### Loki and Promtail for logs #####
  loki:
    image: grafana/loki:2.7.0
    user: root
    command:
      - -config.file=/etc/loki/local-config.yml
    volumes:
      - ./config/loki/local-config.yml:/etc/loki/local-config.yml
      - ./config/loki/recording-rules.yml:/etc/loki/rules/fake/recording-rules.yaml
      - loki-data:/data:rw
  promtail:
    image: grafana/promtail:2.7.0
    command:
      - -config.file=/etc/promtail.yml
    volumes:
      - ./config/loki/promtail.yml:/etc/promtail.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro

  ###### Tempo for traces #####
  tempo:
    image: grafana/tempo:1.5.0
    command:
      - -config.file=/etc/tempo/local-config.yml
    volumes:
      - ./config/tempo/local-config.yml:/etc/tempo/local-config.yml
      - tempo-data:/data:rw

  ##### Cadvisor exposes metrics for running containers #####
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  grafana-data:
  prometheus-data:
  loki-data:
  tempo-data:
