version: "3.9"

services:
  ##### Grafana for visualization #####
  grafana:
    image: grafana/grafana:9.3.1
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
