server:
  log_level: info
  http_listen_port: 9080

clients:
  - url: http://loki:3100/loki/api/v1/push
positions:
  filename: /tmp/positions.yaml
scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    pipeline_stages:
      - docker: { }
      - static_labels:
          job: "promtail"
    relabel_configs:
      - source_labels:
          - '__meta_docker_container_name'
        regex: '(.*)'
        target_label: 'container'