groups:
  - name: Grafana
    interval: 1m
    rules:
      - record: grafana_request_completed:rate1m
        expr: |
          rate(
            {container="/ugr-isew-lab-grafana-1"}
            |= "Request Completed"
            [1m]
          )
      - record: requests_status:rate1m
        expr: |
          sum by (service, status) (
            rate (
              {service=~".+"}
              |= "status="
              | pattern "<_> status=<status> <_>"
              [1m]
            )
          )
      - record: requests_total:rate1m
        expr: |
          sum by (service) (
            rate (
              {service=~".+"}
              |= "status="
              [1m]
            )
          )