groups:
- name: ServiceRules
  interval: 30s
  rules:
    - record: requests_status:rate1m
      expr: |
        sum by (service, status) (
          rate (
            {service=~".+"}
            |= "status="
            | pattern "<_> status=<status> <_>"
            [1m]
          )
        )
    - record: requests_total:rate1m
      expr: |
        sum by (service) (
          rate (
            {service=~".+"}
            |= "status="
            [1m]
          )
        )