{
 "title": "Services Overview",
 "tags": [
  "microbs",
  "ecommerce"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Downtime Budget Remaining this month",
   "type": "stat",
   "description": "* 168 = the SLO (2 minutes 48 seconds) in seconds\n*  (sum(count_over_time((probe_success{probe=\"Private Probe\"} == 0)[30d:])) == How many failed probes where there in the last 30 days\n* / 7 == there are 7 services so normalise it back down to a service perspective\n* 10 == the synthetic monitoring checks run every 10 seconds so this takes the above everything which is how many windows failed and converts that to seconds\n",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "300 - (sum(count_over_time((probe_success{probe=\"Private Probe\"} == 0)[30d:])) / 7 * 10) or vector(300)"
    }
   ]
  },
  {
   "title": "Downtime SLO (fixed) this month",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "vector(5)" }
   ]
  },
  {
   "title": "Payment Error Failure Budget Remaining This Month",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "500 - (sum(count_over_time({service=\"payment\"} | logfmt | endpoint = `/process` | status != `200` [30d])) or vector(0))",
     "legendFormat": "RemainingErrors"
    }
   ]
  },
  {
   "title": "Payment Failure SLO (fixed)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "vector(500)" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "options": {
    "content": "<div style=\"height:100%;width:100%;display:flex;align-items:end;text-align:center;\">\n  <h4>api-gateway</h4>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "<div style=\"height:100%;width:100%;display:flex;align-items:end;text-align:center;\">\n  <h4>web-gateway</h4>\n</div>"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The fraction of time the target was up during the whole period.",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n  (\n    ceil(\n      sum by (instance, job) (increase(probe_all_success_sum{instance=\"http://api-gateway.default.svc.cluster.local/\", job=\"ecommerce-api-gateway\"}[5m]))\n      /\n      sum by (instance, job) (increase(probe_all_success_count{instance=\"http://api-gateway.default.svc.cluster.local/\", job=\"ecommerce-api-gateway\"}[5m]))\n    )\n  )[$__range:]\n)\n/\ncount_over_time(\n  (\n      sum by (instance, job) (increase(probe_all_success_count{instance=\"http://api-gateway.default.svc.cluster.local/\", job=\"ecommerce-api-gateway\"}[5m]))\n  )[$__range:]\n)"
    }
   ]
  },
  {
   "title": "Reachability",
   "type": "stat",
   "description": "The percentage of all the checks that have succeeded during the whole time period.",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(probe_all_success_sum{instance=\"http://api-gateway.default.svc.cluster.local/\", job=\"ecommerce-api-gateway\"}[$__range])\n   )\n/\nsum(\n  increase(probe_all_success_count{instance=\"http://api-gateway.default.svc.cluster.local/\", job=\"ecommerce-api-gateway\"}[$__range])\n)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The fraction of time the target was up during the whole period.",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n  (\n    ceil(\n      sum by (instance, job) (increase(probe_all_success_sum{instance=\"http://web-gateway.default.svc.cluster.local/\", job=\"ecommerce-web-gateway\"}[5m]))\n      /\n      sum by (instance, job) (increase(probe_all_success_count{instance=\"http://web-gateway.default.svc.cluster.local/\", job=\"ecommerce-web-gateway\"}[5m]))\n    )\n  )[$__range:]\n)\n/\ncount_over_time(\n  (\n      sum by (instance, job) (increase(probe_all_success_count{instance=\"http://web-gateway.default.svc.cluster.local/\", job=\"ecommerce-web-gateway\"}[5m]))\n  )[$__range:]\n)"
    }
   ]
  },
  {
   "title": "Reachability",
   "type": "stat",
   "description": "The percentage of all the checks that have succeeded during the whole time period.",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(probe_all_success_sum{instance=\"http://web-gateway.default.svc.cluster.local/\", job=\"ecommerce-web-gateway\"}[$__range])\n   )\n/\nsum(\n  increase(probe_all_success_count{instance=\"http://web-gateway.default.svc.cluster.local/\", job=\"ecommerce-web-gateway\"}[$__range])\n)"
    }
   ]
  },
  {
   "title": "Application Architecture",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 18, "w": 10, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(probe_success{job=\"ecommerce-web-gateway\"})",
     "legendFormat": "WebGateway"
    },
    {
     "expr": "(probe_success{job=\"ecommerce-api-gateway\"})",
     "legendFormat": "APIGateway"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service_name=\"product\"}[1m])) by (le)) * 1) > bool 2000 or (probe_success{job=\"ecommerce-product\"}) == bool 0 or {name=\"ProductDBErrors\"} > bool 0",
     "legendFormat": "ProductSLI"
    },
    {
     "expr": "ProductDBErrors{name=\"ProductDBErrors\"}",
     "legendFormat": "ProductDB"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service_name=\"cart\"}[1m])) by (le)) * 1) or (probe_success{job=\"ecommerce-cart\"}) == bool 0",
     "legendFormat": "Cart"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service_name=\"checkout\"}[1m])) by (le)) * 1) or (probe_success{job=\"ecommerce-checkout\"}) == bool 0",
     "legendFormat": "Checkout"
    },
    {
     "expr": "(histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service_name=\"content\"}[1m])) by (le)) * 1) or (probe_success{job=\"ecommerce-content\"}) == bool 0",
     "legendFormat": "Content"
    },
    {
     "expr": " sum_over_time(PaymentProcessErrors1m[1m]) > bool 0",
     "legendFormat": "Payment"
    },
    { "expr": "SessionDBErrors{}", "legendFormat": "SessionDb" },
    { "expr": "CartDBErrors{}", "legendFormat": "CartDb" }
   ]
  },
  {
   "title": "Service Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{}[1m])) by (service_name)",
     "legendFormat": "{{ service_name }}"
    },
    {
     "expr": "sum(sum(rate(traces_spanmetrics_calls_total{}[1m])) by (service_name))",
     "legendFormat": "(total)"
    }
   ]
  },
  {
   "title": "Service Error Rate by Service",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{event_outcome=\"failure\"}[1m])) by (service_name)\n/\nsum(rate(traces_spanmetrics_calls_total[1m])) by (service_name)",
     "legendFormat": "{{ service_name }}"
    }
   ]
  },
  {
   "title": "Service Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{}[1m])) by(le, service_name)) * 1",
     "legendFormat": "{{ service_name }}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{}[1m])) by (le)) * 1",
     "legendFormat": "(average)"
    }
   ]
  }
 ]
}