global:
  scrape_interval: 10s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'grafana:3000'
          - 'cadvisor:8080'